# Generated by Django 4.2 on 2025-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='website_settings')),
                ('site_favicon', models.ImageField(upload_to='website_settings')),
                ('facebook_url', models.URLField()),
                ('whatsApp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('youtube_url', models.URLField()),
            ],
        ),
    ]
