# Generated by Django 4.2 on 2025-01-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0002_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='google_map_link',
            field=models.URLField(),
        ),
    ]
