# Generated by Django 4.2 on 2025-01-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0003_alter_store_google_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
