# Generated by Django 4.2 on 2025-01-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0007_alter_privacypolicy_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
