# Generated by Django 4.2 on 2025-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0009_alter_termsandconditions_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
