# Generated by Django 4.2 on 2025-01-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0010_alter_termsandconditions_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
