# Generated by Django 4.2 on 2025-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0011_alter_termsandconditions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
