# Generated by Django 4.2 on 2025-01-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0012_alter_termsandconditions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsandconditions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
