# Generated by Django 4.2 on 2025-01-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_Settings', '0013_alter_termsandconditions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
