# Generated by Django 4.2 on 2025-01-15 19:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='devices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchiseApplicantFirstName', models.CharField(max_length=100)),
                ('franchiseApplicantLastName', models.CharField(max_length=100)),
                ('franchiseApplicantEmail', models.EmailField(max_length=254, unique=True)),
                ('franchiseApplicantPhone', models.CharField(max_length=15)),
                ('franchiseApplicantStreetAddress', models.CharField(max_length=200)),
                ('aboutFranchiseApplicant', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FranchiseSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor.fields.RichTextField(max_length=150)),
                ('subtitle', models.TextField()),
                ('image', models.ImageField(upload_to='slider/')),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=200)),
                ('link_type', models.CharField(choices=[('url', 'External URL'), ('tel', 'Phone Link'), ('scroll', 'Scroll to Section')], default='url', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.franchisesections')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('customerFirstName', models.CharField(max_length=100)),
                ('customerLastName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerPhone', models.CharField(max_length=15)),
                ('deviceImages', models.FileField(upload_to='device_images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.model')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device'),
        ),
    ]
