# Generated by Django 4.2 on 2025-01-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_devicesell_deviceimages_deviceimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceImage',
            new_name='DeviceSellImage',
        ),
    ]
