# Generated by Django 4.2 on 2025-01-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_brand_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
