# Generated by Django 4.2 on 2025-01-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_brand_name_alter_model_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('customerFirstName', models.CharField(max_length=100)),
                ('customerLastName', models.CharField(max_length=100)),
                ('customerEmail', models.EmailField(max_length=254)),
                ('customerPhone', models.CharField(max_length=15)),
                ('deviceImages', models.ImageField(blank=True, null=True, upload_to='device_images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
