# Generated by Django 4.2 on 2025-01-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_devicesell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesell',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brand'),
        ),
        migrations.AlterField(
            model_name='devicesell',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.model'),
        ),
        migrations.AlterField(
            model_name='devicesell',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.device'),
        ),
    ]
