# Generated by Django 4.2 on 2025-01-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_devicesell_brand_alter_devicesell_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesell',
            name='deviceImages',
            field=models.ImageField(default=1, upload_to='device_images/'),
            preserve_default=False,
        ),
    ]
