# Generated by Django 4.2 on 2025-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_devicesell_deviceimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesell',
            name='deviceImages',
            field=models.FileField(upload_to='device_images/'),
        ),
    ]
