# Generated by Django 4.2 on 2025-01-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_devicesell_deviceimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=100)),
            ],
        ),
    ]
