# Generated by Django 4.2 on 2025-01-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_franchisefeatures_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FranchiseFeatures',
            new_name='Features',
        ),
    ]
