# Generated by Django 4.2 on 2025-01-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_franchisefeatures_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('franchiseApplicantFirstName', models.CharField(max_length=100)),
                ('franchiseApplicantLastName', models.CharField(max_length=100)),
                ('franchiseApplicantEmail', models.EmailField(max_length=254, unique=True)),
                ('franchiseApplicantPhone', models.CharField(max_length=15)),
                ('franchiseApplicantStreetAddress', models.CharField(max_length=200)),
                ('aboutFranchiseApplicant', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='features',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='home.franchisesections'),
        ),
    ]
