# Generated by Django 4.2 on 2025-01-21 18:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_slider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=ckeditor.fields.RichTextField(max_length=500),
        ),
    ]
