# Generated by Django 4.2 on 2025-01-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_device_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='slug',
        ),
    ]
