# Generated by Django 4.2 on 2025-02-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_device_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='si_no',
            field=models.PositiveIntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
