# Generated by Django 5.1.6 on 2025-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_device_si_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='si_no',
            field=models.PositiveIntegerField(),
        ),
    ]
