# Generated by Django 4.2 on 2025-01-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcategory',
            old_name='name',
            new_name='title',
        ),
    ]
