# Generated by Django 4.2 on 2025-01-15 20:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_rename_name_jobcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingjob',
            name='requirements',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='openingjob',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
